### ISSUE TITLE
=NOW() =SECOND(NOW()) works wrong

### ISSUE THREAD

**Issue by vinnik-dmitry07** [unvell/ReoGrid#204]
=NOW() - outs just date.
=SECOND(NOW()) - outs date for example 15.02.1900.
Partial fix is to add: CurrentWorksheet.SetSettings(WorksheetSettings.Edit_AutoFormatCell, false);
I think mistake is in DataFormats.cs/DateTimeDataFormatter.

**Comment by 3Pi0FomTatuin** [comment]
It happens because NOW does this:
`cell.DataFormat = DataFormat.CellDataFormatFlag.DateTime;
cell.DataFormatArgs = new DataFormat.DateTimeDataFormatter.DateTimeFormatArgs
{
    Format = "yyyy/MM/dd HH:mm",
    CultureName = "en-US",
};`
So my fix:
`case BuiltinFunctionNames.SECOND_EN:
case BuiltinFunctionNames.SECOND_RU:
    dt = (DateTime)GetFunctionArg(cell, funNode.Children, FormulaValueType.DateTime);
    cell.DataFormat = DataFormat.CellDataFormatFlag.General;
    return dt.Second;`
But I'm not fully sure that It is the best way of solving.

**Comment by jingwood** [comment]
similar bug https://github.com/unvell/ReoGrid/issues/204

**Comment by jingwood** [comment]
I think this has been resolved by #310. If there is still the problem, please let me know. Thanks!
