### ISSUE TITLE
Third party licence agreement

### ISSUE THREAD

**Issue by steven11980** [unvell/ReoGrid#218]
The ReoGrid license agreement mentions the following:

**Third-party

This software may contain the following software:
- ReoScript
- ANTLR v3
- FastColoredTextBox
- DotNetZip**

ReoGrid says it's free. What are the implications of these third party software to the license?

If I download the ReoGridWPF.dll to use in my product will I have to also include these DLLs?

**Comment by jingwood** [comment]
## Short answer

ReoGrid it fully free for commercial applications.

## Long answer

Different release edition have different license requirements. But all dependencies available for commercial applications.

### ReoGrid

ReoGrid's three release editions:

1. Minimal features edition (Single `ReoGrid.DLL` or `ReoGridWPF.dll`) 
2. Standard features (Single `ReoGrid.DLL` or `ReoGridWPF.dll`)
3. Extension features (Multiple DLL including third-party)

The first release include minimal features with single DLL which doesn't require third party DLL, it is fully available on MIT license.

The second release include standard features with single DLL which requires only DotNetZip module, it is available on MS-PL license. (same as NuGet edition)

The third release requires ReoScript (MIT) and ANTLR v3 (BSD).

### ReoGrid Editor

ReoGrid Editor includes FastColoredTextBox package which is released under LGPLv3, you can only reference it's DLL in your application folder.

### Remark

Since both ReoGrid and ReoGrid Editor is released under MIT license, you can feel free to remove feature and code that depend on other third-party module.

**Comment by datadiode** [comment]
Just in case you like the idea to not rule out the GNU world through MS-PL:
https://github.com/datadiode/ReoGrid/commit/d4ffb3c5264cfb1e211aecfbc1ca4c16cb0a4cac

BTW, ReoGrid/Utility/ZipFileArchive.cs still says ReoGrid is LGPLv3.
