### ISSUE TITLE
Question: Can I print a shet im thermal printer?

### ISSUE THREAD

**Issue by dquinter** [unvell/ReoGrid#269]
Hi all.

I have a sales ticket in a sheet of ReoGrid, and I want to print it on a thermal printer, where I know the width of the sheet, but not the height. The height is dynamic, depending on the amount of products in the sale.

I mean, I want to print the ticket on a roll of paper without intermediate page breaks.

It's possible?

My sales ticket is similar to the following image
![image](https://user-images.githubusercontent.com/28767938/63046664-8e1bbe00-be98-11e9-8729-5711c66809a3.png)

Thanks in advance.

**Comment by jingwood** [comment]
Hi @dquinter, during try to implement the feature you mentioned, I found a bug in ReoGrid and now it has been fixed. Please download the latest source code and build DLL from the source code rather than using release packages.

To implement your requirement, you have to change the worksheet page breaks. 

By default, ReoGrid splits worksheet into multiple page, but in your case, you need only one page. So by changing the horizontal page breaks to remove any page breaks between start and end rows.

1. When your worksheet is ready, use following to create default page breaks
```cs
sheet.AutoSplitPage();
```

2. Use following code to force make all content to be printed inside one page

```cs
sheet.ChangeColumnPageBreak(sheet.ColumnPageBreaks[1], sheet.UsedRange.EndCol + 1);
sheet.ChangeRowPageBreak(sheet.RowPageBreaks[1], sheet.UsedRange.EndRow + 1);
```

This code means that change the second column and row page breaks to the last data cell.

*Note again*: Please use the latest source code.

Learn more at https://reogrid.net/document/paging-and-print/

**Comment by dquinter** [comment]
Hi @jingwood 

You are the best. Thanks for all!

I'm going to implement your recommendations :-)
