### ISSUE TITLE
AutoFillSerial with text

### ISSUE THREAD

**Issue by Xcone** [unvell/ReoGrid#61]
Hi Jing, 

The first version of an editor in our software which is powered by Reogrid is close to getting used in the field. As part of our tests we're getting feedback that AutoFillSerial doesn't support text. 

Examples would be:
[Text] AutoFillSerial to [Text][Text][Text]
[Text1] AutoFillSerial to [Text1][Text2][Text3]

You may remember I recently made changes to AutoFillSerial in regards of refactoring, and protecting Read-Only cells. I'd be happy to build this myself, but only if you're interested in merging it back. As I wish to stick to the version of Reogrid that is maintained by you. 

So, is this something you wish to include to Reogrid?

**Comment by Xcone** [comment]
If you're interested, please let me know how exactly to match to Excel. I've been toying around in Excel and in ReoGrid and noticed the numbering logic is not identical. Sequential values work fine
[2][4][6] fills to [8][10][12]

Non sequenctial fills are inconsistent though:
[1][5][3] in ReoGrid turns into [4][8][6]. Which is nice. It follows the pattern and the avarage increase of the 3 cells.
In excel it fills to [5],[6],[7]. I have no clue what the math behind that is supposed to be.

A longer sequence is a mess in both, though.
Reogrid: [1],[4],[2],[5],[3],[6]. With an avarage increase of 1 per cell I would've expected: [4],[7],[5],[8],[6],[9]. But instead Reogrid produces: [9,625][12,625][10,625][13,625][11,625][14,625]. The pattern is there, but the calculation of the avarage increase per cell is bust.
Same fill in excel produces: [6][6,714286][7,428571][8,142857][8,857143][9,571429] which makes no sense at all.

In a similar way I've also been toying around with textual auto fills, both with and without combing the text with numbers. The pattern handling in Excel seems a lot more sensible in this area.

So, given the numerical fills are not identical between Reogrid and Excel. Would you say textual fill (with or without numbers) should be as identical to Excel as possible? Or doesn't it matter much as long as it follows something sensible?

Would you mind changes in the existing calculations (for instance the avarage-calculation which produces a weird result as stated earlier)? Or are these rules and calculations as intended and would you prefer to keep it as it is?

**Comment by jingwood** [comment]
Hi @Xcone,

Thanks! It sounds nice to me, to support the [text-number] pattern fill. I would like to merge it back and make the NuGet package including it. (sorry for late for current release)

> So, given the numerical fills are not identical between Reogrid and Excel. Would you say textual fill (with or without numbers) should be as identical to Excel as possible? Or doesn't it matter much as long as it follows something sensible?

Both are good to me. Just as you mentioned sometimes the Excel returns a nonsense serial result, like:

| | input | output | 
|-|-|-|
| Excel | 1, 5, 3 | 1, 5, 3, 5, 6, 7 |
| ReoGrid | 1, 5, 3 | 1, 5, 3, 4, 8, 6 |

In this sample I think the result from ReoGrid is more helpful to end-user. So I tend to keep the current logic. But if users report that they meet problems since the different calculation pattern I will consider to change it to be same as Excel, or consider to add an option or provide something like overloadable function which can be replaced with user logic. 

Looking forward to this change, if there is something I can help please let me know.

**Comment by Xcone** [comment]
Alright, I'll get to it! :-)

Practical question. I noticed you're code has it's own proprietary test suite. Is there a particular benefit for that? Why not use some commonly used test suite, like NUnit?

Would you mind if I added tests for autofill serial as NUnit, as I can easily run that from the Visual Studio test-runner or Resharper test runner without having to start an application. Or can I start a subset of tests with your test tools as well?

**Comment by jingwood** [comment]
> Is there a particular benefit for that? Why not use some commonly used test suite, like NUnit?

I use proprietary test framework because I want to reduce the external package dependency in the past, to make running test cases from different computers, OS and language environment more easily, including the environment of end-user, or environment without Visual Studio installed.

> Would you mind if I added tests for autofill serial as NUnit, as I can easily run that from the Visual Studio test-runner or Resharper test runner without having to start an application.

No problem, you can use your preferred way to do tests. Also no problem if you import the new test framework that is based on NUnit, I will try to use it.

**Comment by jingwood** [comment]
New version with NuGet package has been released. Thanks @Xcone!

**Comment by Xcone** [comment]
No problem! And thank you too for the release! :-)
